project:
  type: website

website:
  title: "UP-RISE Project"
  navbar:
    left:
      - text: "Home"
        href: "index.qmd"
      - text: "Publications"
        href: "publications.qmd"
      - text: "Team"
        href: "people.qmd"
        
format:
  html:
    theme: flatly
    toc: false
    page-layout: full
    css: styles.css
